[versions]

kotlin = "1.8.10"
androidGradle = "7.3.0"
mdi = "0.0.7"

[libraries]

# gradle plugins
kotlinPlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidPlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
